//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizLgpdGameApi.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gamequizlgpdEntities : DbContext
    {
        public gamequizlgpdEntities()
            : base("name=gamequizlgpdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NiveisDificuldades> NiveisDificuldades { get; set; }
        public virtual DbSet<Questoes> Questoes { get; set; }
        public virtual DbSet<RepostasUsuarios> RepostasUsuarios { get; set; }
        public virtual DbSet<Respostas> Respostas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
