//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizLgpdGameApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiveisDificuldades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NiveisDificuldades()
        {
            this.Questoes = new HashSet<Questoes>();
        }
    
        public int Id { get; set; }
        public string Dificuldade { get; set; }
        public int Pontos { get; set; }
        public int Dano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questoes> Questoes { get; set; }
    }
}
