//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizLgpdGameApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questoes()
        {
            this.RepostasUsuarios = new HashSet<RepostasUsuarios>();
            this.Respostas = new HashSet<Respostas>();
        }
    
        public int Id { get; set; }
        public int NiveisDificuldadesId { get; set; }
        public string Questao { get; set; }
    
        public virtual NiveisDificuldades NiveisDificuldades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepostasUsuarios> RepostasUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respostas> Respostas { get; set; }
    }
}
