//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizLgpdGameApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepostasUsuarios
    {
        public int Id { get; set; }
        public int QuestaoId { get; set; }
        public int RespostaId { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Questoes Questoes { get; set; }
        public virtual Respostas Respostas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
