//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizLgpdGameApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respostas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respostas()
        {
            this.RepostasUsuarios = new HashSet<RepostasUsuarios>();
        }
    
        public int Id { get; set; }
        public int QuestaoId { get; set; }
        public string Resposta { get; set; }
        public bool RespostaCorreta { get; set; }
    
        public virtual Questoes Questoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepostasUsuarios> RepostasUsuarios { get; set; }
    }
}
